#
# Servers #
#
bind_to_address    "127.0.0.1"
auto_update        "yes"
db_file            "~/.local/share/mpd/database"
log_file           "~/.local/share/mpd/log"
pid_file           "~/.local/share/mpd/pid"
port               "6600"
state_file         "~/.local/share/mpd/state"

#
# Directory #
#
music_directory    "~/Music"
playlist_directory "~/.local/share/mpd/playlists"

#
# Other's #
#
filesystem_charset "UTF-8"


#
# Audio Output #
# to get audio type use this command $ aplay --list-pcm
#

# audio_output {
#   type "alsa"
#   name "Shanling UA4"
#   device "iec958:CARD=UA4,DEV=0"
#   mixer_control "PCM"
# }

audio_output {
    type   "pipewire"
    name   "PipeWire Sound Server"
    device "pipewire"
}
