#! /bin/sh
#
# Startup Applications
#
$HOME/.config/bspwm/autostart

#
# define colorscheme
#
focus="#ebdbb2"
normal="#504945"

#
# Workspace
#
bspc monitor eDP-1 -d 1 2 3 4 5

#
# Window Configurations
#
bspc config border_width 2
bspc config window_gap 5
bspc config top_padding 28
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

#
# User Interface
#
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config ignore_ewmh_fullscreen none
bspc config ignore_ewmh_focus false
bspc config remove_unplugged_monitors true
bspc config normal_border_color $normal
bspc config active_border_color $focus
bspc config focused_border_color $focus

#
# Window Rules
#
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
