#! /bin/sh


#
# Startup Applications
#
$HOME/.config/bspwm/autostart


#
# Workspace
#
bspc monitor LVDS-1 -d 1 2 3 4 5
bspc monitor VGA-1 -d 6 7 8 9 10


#
# Window Configurations
#
bspc config border_width   2
bspc config border_radius  5
bspc config window_gap     5
bspc config top_padding    0
bspc config bottom_padding 0
bspc config right_padding  0
bspc config left_padding   0

#
# User Interface
#
bspc config split_ratio               0.50
bspc config borderless_monocle        false
bspc config gapless_monocle           true
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
bspc config ignore_ewmh_fullscreen    all
bspc config ignore_ewmh_focus         false
bspc config remove_unplugged_monitors true
bspc config normal_border_color       "#a89984"
bspc config active_border_color       "#d79921"
bspc config focused_border_color      "#d79921"

#
# Window Rules
#
bspc rule -a Screenkey manage=off
bspc rule -a key-mon manage=off
