#!/bin/bash

update() {
	sum=0
	for arg; do
		read -r i <"$arg"
		sum=$((sum + i))
	done
	cache=${XDG_CACHE_HOME:-$HOME/.cache}/${1##*/}
	[ -f "$cache" ] && read -r old <"$cache" || old=0
	printf %d\\n "$sum" >"$cache"
	printf %d\\n $((sum - old))
}

rx=$(update /sys/class/net/wlan0/statistics/rx_bytes)
tx=$(update /sys/class/net/wlan0/statistics/tx_bytes)

case $1 in
    up) printf "%4sB" $(numfmt --to=iec $tx) ;;
    down) printf "%4sB" $(numfmt --to=iec $rx) ;;
esac
