#!/bin/bash

if pgrep bspwm; then
    pid="$(ps -eo pid,args --cols=10000 | awk '/config.ini bspwmTop/ && $1 != PROCINFO["pid"] { print $1 }')"
    for p in $pid; do
        bspc config top_padding 0
        polybar-msg -p $p cmd toggle
    done
else
    pid="$(ps -eo pid,args --cols=10000 | awk '/config.ini i3wmTop/ && $1 != PROCINFO["pid"] { print $1 }')"
    for p in $pid; do
        polybar-msg -p $p cmd toggle
    done
fi
