#!/bin/bash
pid="$(ps -eo pid,args --cols=10000 | awk '/config.ini bspwmTop/ && $1 != PROCINFO["pid"] { print $1 }')"
for p in $pid; do
    bspc config top_padding 0
    polybar-msg -p $p cmd toggle
done
