require("awful.autofocus")
require("modules.errorhandler")
require("modules.decoration")
require("modules.signal")
require("modules.screen")
require("modules.keymap")
require("modules.rules")
require("modules.autostart")
