complete --command eww --exclusive --long help --description "Show help"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments close --description "Close the given windows"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments close-all --description "Close all windows, without killing the daemon"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments daemon --description "Start the Eww daemon"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments debug --description "Print out the widget structure as seen by eww"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments get --description "Get the value of a variable if defined"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments graph --description "Print out the scope graph structure in graphviz dot format"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments inspector --description "Open the GTK debugger"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments kill --description "Kill the eww daemon"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments logs --description "Print and watch the eww logs"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments open --description "Open a window"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments open-many --description "Open multiple windows at once. NOTE: This will in the future be part of eww open, and will then be removed"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments ping --description "Ping the eww server, checking if it is reachable"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments reload --description "Reload the configuration"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments state --description "Prints the variables used in all currently open window"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments update --description "Update the value of a variable, in a running eww instance"
complete --command eww --exclusive --condition __fish_use_subcommand --arguments windows --description "Print the names of all configured windows. Windows with a * in front of them are currently opened"
