#!/bin/sh

map f fzf_select
map D delete
map x &dragon-drop -a -x $fx
map R reload

# Directory
map gM cd /run/media/
map gm cd /mnt/
map gt cd /tmp/

# yank file name
map Yn &echo -n $(basename "$f") | wl-copy
map Yp &echo -n "$f" | wl-copy
map Yd &echo -n $(dirname "$f") | wl-copy

# ratios
map <a-0> set ratios 1:3:2
map <a-1> :set nopreview; set ratios 1
map <a-2> :set preview; set ratios 2:2
map <a-3> :set preview; set ratios 1:2:3
