#!/bin/bash

if [ "$(pwd)" != "/tmp/rclone" ]; then
	case $(file --mime-type "$1" -bL) in
        application/zip) unzip -l "$1" ;;
        application/x-shellscript) cat "$1" ;;
        application/x-7z-compressed) 7z l "$1" ;;
        application/gzip) tar -tvf "$1" ;;
        application/x-iso9660-image) iso-info --no-header -f "$1" ;;
        text/*) cat "$1" ;;
        *) mediainfo "$1" ;;
	esac
fi
