# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = ["M", "d"], run = "plugin mount", desc = "A mount manager for Yazi" },
  { on = [
    "M",
    "s",
  ], run = "plugin sshfs -- menu", desc = "Open SSHFS options" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
]

append_keymap = [
  { on = "<C-o>", run = "shell -- dragon-drop -x -i -T %s1", desc = "Drag & drop file (dragon)" },
]


[input]
prepend_keymap = [{ on = "<Esc>", run = "close", desc = "Cancel input" }]
