# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
append_keymap = [
  { on = "<C-o>", run = "shell -- dragon-drop -x -i -T %s1", desc = "Drag & drop file (dragon)" },
]
