"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[mgr]
border_symbol = " "


[indicator]
parent = { fg = "black", bg = "white" }
current = { fg = "black", bg = "white" }
preview = { hidden = true }
padding = { open = "█", close = "█" }


[tabs]
active = { bg = "gray", fg = "black", bold = true }
inactive = { fg = "reset", bg = "reset" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }


[status]
overall = {}
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }


[mode]
normal_main = { bg = "reset", bold = true }
normal_alt = { fg = "reset", bg = "reset" }

select_main = { bg = "red", bold = true }
select_alt = { fg = "red", bg = "gray" }

unset_main = { bg = "red", bold = true }
unset_alt = { fg = "red", bg = "gray" }
