# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = false
linemode = "none"
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "Yazi: {cwd}"

[opener]
play = [
	{ run = "mpv %s", orphan = true, for = "unix" },
]
set-wallpaper = [
  { run = "awww img '%s1'", for = "linux", desc = "Set as wallpaper", orphan = true },
]

[open]
prepend_rules = [{ mime = "image/*", use = ["open", "set-wallpaper"] }]

[plugin]
prepend_fetchers = [
  { id = "mime", url = "local:///tmp/sshfs/*", run = "mime-ext.remote", prio = "high" },
  { id = "mime", url = "local://*", run = "mime-ext.local", prio = "high" },
  { id = "mime", url = "remote://*", run = "mime-ext.remote", prio = "high" }
]

