#!/bin/sh

function run() {
	if [[ -z "$(pidof $1)" ]]; then
		$@ &
	fi
}

run systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
run dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway
run /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
run wl-paste --watch cliphist store
run batsignal -b -c 20 -w 25 -d 15 -D "systemctl suspend"
run dunst
run waybar
run swww-daemon
