#!/bin/sh

touchpad=pointer-1267-12632-ELAN050A:01_04F3:3158_Touchpad

# Enable or disable the tap functionality of the input device.
riverctl input $touchpad tap enabled

# Enable tap-and-drag functionality of the input device.
riverctl input $touchpad drag enabled

# Set the pointer acceleration profile of the input device.
riverctl input $touchpad accel-profile none

# Set the pointer acceleration factor of the input device. Needs a float between -1.0 and 1.0.
riverctl input $touchpad pointer-accel 0.3

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set background color
riverctl background-color 0x282828

# Enabled server side decorations
riverctl rule-add ssd

# Autofocus to spesific output by cursor
riverctl focus-follows-cursor disabled

# RULES
riverctl rule-add -app-id Pinentry-gtk float
riverctl rule-add -app-id xdg-desktop-portal-gtk float
riverctl rule-add -app-id nm-connection-editor float
riverctl rule-add -app-id com.usebottles.bottles csd
riverctl rule-add -app-id wpsoffice csd
