#!/bin/sh

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile

# Set border color
riverctl border-color-focused 0xebdbb2
riverctl border-color-unfocused 0x504945

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Control+{H,J,K,L} to change layout orientation
riverctl map normal Super+Control K send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Control L send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Control J send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Control H send-layout-cmd rivertile "main-location left"

riverctl spawn 'rivertile -view-padding 6 -outer-padding 6 -main-ratio 0.7'
