#!/bin/sh

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout wideriver

# Super+Space to toggle layout
riverctl map normal Super Space send-layout-cmd wideriver '--layout-toggle'

# Super+Plus to increase master ratio
riverctl map normal Super plus send-layout-cmd wideriver "--ratio +0.01"
# Super+Equal to set default master ratio
riverctl map normal Super equal send-layout-cmd wideriver "--ratio 0.5"
# Super+Minus to decrease master ratio
riverctl map normal Super minus send-layout-cmd wideriver "--ratio -0.01"

# start layout manager
riverctl spawn 'wideriver --layout left --ratio-master 0.5 --stack even --outer-gaps 5 --inner-gaps 5 --border-color-focused "0xebdbb2" --border-color-unfocused "0x665c54" --layout-alt monocle --border-width 3 --border-width-monocle 3 --no-smart-gaps --border-color-focused-monocle "0xebdbb2"'
