#!/bin/bash
# dmenu_mpv
# Copyright (c) 2020 M. Nabil Adani <nblid48[at]gmail[dot]com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Required
# 1. mpv
# 2. rofi
# 3. openbsd-netcat
# 4. jq

DMENU="rofi -dmenu -i"
SOCKET=${MPVC_SOCKET:-/tmp/mpvsocket}
SOCKETCOMMAND="nc -U -N $SOCKET"

getPlaylist() {
	echo '{ "command": ["get_property_string", "playlist"] }' | $SOCKETCOMMAND | jq ".data | fromjson"
}

play() {
	query=$(jq --null-input --arg id $1 '{ "command": ["set_property_string", "playlist-pos-1", $id] }')
	echo $query | $SOCKETCOMMAND
}

playlist=$(getPlaylist)
filename=$(echo $playlist | jq -r '.[].filename' | $DMENU -p "奈 MPV")
play $(echo $playlist | jq ".[] | select(.filename==\"$filename\") | .id")
