#!/bin/bash
# File              : dmenu_ytview
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Kamis, 05/09/2019 11:08 WIB
# Last Modified Date: Sabtu, 14/03/2020 06:49 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>

# inspired by https://github.com/harimurtie/ndotfiles/blob/master/scripts/ytplay

# Required:
# 1. youtube-viewer

resolution="144p\n240p\n360p\n480p\n720p\n1080p"
selected=$(echo -e "$resolution" | rofi -dmenu -i -p YouTube -lines 6 $@)
url="$(xclip -selection clipboard -o | cut -d '&' -f 1)"

case "$selected" in
144p) youtube-viewer --auto-caption --resolution 144p $url ;;
240p) youtube-viewer --auto-caption --resolution 240p $url ;;
360p) youtube-viewer --auto-caption --resolution 360p $url ;;
480p) youtube-viewer --auto-caption --resolution 480p $url ;;
720p) youtube-viewer --auto-caption --resolution 720p $url ;;
1080p) youtube-viewer --auto-caption --resolution 1080p $url ;;
esac
