#!/bin/bash
# File              : dmenu_mager
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Jumat, 15/05/2020 13:12 WIB
# Last Modified Date: Jumat, 19/06/2020 10:47 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>

DMENU="rofi -dmenu -i -p Mager"
OPTIONS=$(echo "anime aria2 boottester kill monitor mpdmenu pass power qutebrowser record switcher systemd todo udiskie wifi window ytview mpv screenshot translate sxhkd droidcam scrcpy" | sed 's/\ /\n/g'| sort | $DMENU)

case "$OPTIONS" in
    anime) dmenu_anime ;;
    aria2) dmenu_aria2 ;;
    boottester) dmenu_boottester ;;
    kill) dmenu_kill ;;
    monitor) dmenu_monitor ;;
    mpdmenu) dmenu_mpdmenu ;;
    pass) dmenu_pass -p "Pass Man" ;;
    power) dmenu_power ;;
    qutebrowser) dmenu_qutebrowser ;;
    record) dmenu_record ;;
    switcher) dmenu_switcher ;;
    systemd) dmenu_systemd ;;
    todo) dmenu_todo ;;
    udiskie) dmenu_udiskie -matching regex -dmenu -i -no-custom -multi-select ;;
    wifi) dmenu_wifi ;;
    window) dmenu_window ;;
    ytview) dmenu_ytview ;;
    mpv) dmenu_mpv ;;
    screenshot) dmenu_screenshot ;;
    translate) dmenu_translate ;;
    sxhkd) dmenu_sxhkd ;;
    droidcam) droidcam-cli 192.168.43.1 4747 ;;
    scrcpy) adb connect 192.168.43.1:5555 && scrcpy -b 2M -m 1080 --push-target /sdcard/Download & ;;
esac
