#!/bin/bash
# File              : dmenu_ffmpeg
# License           : MIT License
# Author            : M. Nabil Adani <nblid48[at]gmail[dot]com>
# Date              : Minggu, 28/02/2021 11:41 WIB
# Last Modified Date: Minggu, 28/02/2021 18:06 WIB
# Last Modified By  : M. Nabil Adani <nblid48[at]gmail[dot]com>
# Inspired By       : https://github.com/tanuj101/awesome-dmenu/blob/master/recorder/dmenurecord.sh




DMENU="rofi -dmenu -lines 5 -width 30 -i -p Record"
OUTDIR="$HOME/Videos"
recordid="/tmp/recordid"


function audioVideo() {
    notify-send "Start Recording" "With:\nVideo On\nAudio On"

    filename="$OUTDIR/screencast-$(date '+%y%m%d-%H%M-%S').mkv"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -y  -f x11grab -framerate 30 -s $dimensions \
        -i :0.0 -f alsa -i default -r 30 \
        -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 \
        -c:a aac $filename &

    echo $! > $recordid
}

function video() {
    notify-send "Start Recording" "With:\nVideo On\nAudio Off"

    filename="$OUTDIR/screencast-$(date '+%y%m%d-%H%M-%S').mkv"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -y  -f x11grab -framerate 30 -s $dimensions \
        -i :0.0 -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 $filename &

    echo $! > $recordid
}

function stoprecord(){
    if [ -f $recordid ]; then
        kill -15 $(cat $recordid)
        rm $recordid
    fi
}

function endrecord(){
    OPTIONS='["Yes", "No"]'
    select=$(echo $OPTIONS | jq -r ".[]" | $DMENU -mesg "Stop Recording")
    [ "$select" == "Yes" ] && stoprecord
}

function startrecord(){
    OPTIONS='''
    [
        ["Audio Video", "audioVideo"],
        ["Video Only", "video"]
    ]
    '''
    select=$(echo $OPTIONS | jq -r "sort | .[][0]" | $DMENU)
    eval $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$select\") | .[1]")
}

if [ -f $recordid ]; then
    endrecord
else
    startrecord
fi

