#!/bin/sh
# Repository: https://tools.suckless.org/dmenu/scripts/todo
#
# Write/remove a task to do later.
#
# Select an existing entry to remove it from the file, or type a new entry to
# add it.
#

file="$HOME/.todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="Todo"

cmd=$(dmenu -x 300 -y 220 -w 800 -l "$height" -p "$prompt" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

cmd=$(dmenu -x 300 -y 220 -w 800 -l "$height" -p "$prompt" "$@" < "$file")
done

exit 0
