#!/bin/bash
# File              : dmenu_secret
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Rabu, 10/06/2020 06:45 WIB
# Last Modified Date: Minggu, 02/08/2020 18:15 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>

rofi -dmenu -password -p "$USER" -mesg "Type your password" -theme-str "window {width: 25%;} listview { lines:0;} textbox { horizontal-align: 0.5;}"
