#!/bin/bash
# dmenu_docker
# Copyright (c) 2021 M. Nabil Adani <nblid48[at]gmail[dot]com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

DMENU="rofi -dmenu -i -p Docker"

function get_container() {
    docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}" | $DMENU -selected-row 1 -theme-str "window {width: 55%;}"
}

function menu() {
    OPTIONS='["Start", "Stop", "Restart"]'
    select=$(echo $OPTIONS | jq -r ".[]" | $DMENU -mesg "Container Name : $1" -theme-str 'window {width: 30%;} listview {lines: 1; columns:3;} element-text {horizontal-align: 0.5;}')
    if [ "$select" = "Stop" ]; then
        docker container stop $1 && notify-send "Docker" "Stop : $1"
    elif [ "$select" = "Restart" ]; then
        docker container restart $1 && notify-send "Docker" "Restart : $1"
    elif [ "$select" = "Start" ]; then
        docker container start $1 && notify-send "Docker" "Start : $1"
    fi
}

if [ -f "/run/docker.pid" ]; then
    container=$(get_container)
    if [ "$container" != "" ]; then
        container_name=$(echo $container | cut -d " " -f 2)
        menu $container_name
    fi
else
    notify-send "Docker" "Docker is not running"
fi
