#!/bin/bash
# File              : dmenu_anime
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Sabtu, 28/09/2019 22:10 WIB
# Last Modified Date: Minggu, 29/09/2019 19:06 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>

# Required
# 1. fuseiso
# 2. fusermount
# 3. mpv


OPTIONS="Mount Anime\nPlay Anime\nPlay Playlist\nUmount Anime"
DMENU="dmenu -x 300 -y 220 -w 800 -fn Iosevka-11 -p Anime -l 10 -i"

function mount(){
  fuseiso -p "$(find ~/Anime/*/* -iname '*.iso'|$DMENU)" /tmp/mount
}

function umount(){
  fusermount -u /tmp/iso
}

function play(){
  mpv -vo xv "$(find /tmp/iso/ -iname '*.mkv' -or -iname '*.mp4' | $DMENU)"
}

function play_playlist(){
  mpv -vo xv "/tmp/iso/$(ls /tmp/iso/ | $DMENU)"
}


case "$(echo -e $OPTIONS|$DMENU)" in
  "Mount Anime")  mount;;
  "Play Anime")  play;;
  "Play Playlist")  play_playlist;;
  "Umount Anime")  umount;;
  * )             echo "Perintah tidak tersedia"
    exit 2
esac
