#!/bin/bash
# File              : dmenu_screenshot
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Kamis, 30/07/2020 02:23 WIB
# Last Modified Date: Kamis, 30/07/2020 05:25 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>
# Depends on        : imagemagic, flameshot

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
SCREENSHOTDIR="$HOME/Pictures/screenshot"
ICON="$HOME/Dotfiles/icons/gruvbox/camera.png"
FILENAME="$SCREENSHOTDIR/Screenshot_$TIMESTAMP.png"
DMENU="rofi -dmenu -p Screenshot -lines 3 -width 30"
TEXT="author : mnabila"

takeOnWindow() {
    rofi -e "Select window to capture"
    import $FILENAME
    saveAndCopy
}

takeOnFullScreen() {
    import -window root $FILENAME
    saveAndCopy
}

takeOnRectange() {
    flameshot gui --raw >$FILENAME
    if [[ $(cat $FILENAME) != "screenshot aborted" ]]; then
        saveAndCopy
    else
        rm $FILENAME
    fi
}

addRoundedCorner() {
    convert $FILENAME \( +clone -alpha extract -draw 'fill black polygon 0,0 0,10 10,0 fill white circle 10,10 10,0' \( +clone -flip \) -compose Multiply -composite \( +clone -flop \) -compose Multiply -composite \) -alpha off -compose CopyOpacity -composite $FILENAME
    convert $FILENAME \( +clone -background black -shadow 0x10+0+0 \) +swap -background white -layers merge +repage $FILENAME
}

addBorder() {
    convert $FILENAME -bordercolor "#282828" -border 1 $FILENAME
}

addShadow() {
    convert $FILENAME \( +clone -background black -shadow 30x15+0+0 \) +swap -background white -layers merge +repage $FILENAME
}

addAnnotate() {
    convert $FILENAME -font Iosevka-Nerd-Font-Complete -gravity north -background "#d79921" -fill "#282828" -splice 0x18 -annotate +0+1  "$TEXT" $FILENAME
    # convert $FILENAME -gravity NorthEast -pointsize 20 -fill "#d79921" -undercolor "#d79921" -annotate +60+0 "$TEXT" -pointsize 12 -fill "#282828" -undercolor "#d79921" -font Iosevka-Nerd-Font-Complete -annotate +60+10 "$TEXT" $FILENAME
    # convert $FILENAME -bordercolor "#ff0000" -border 2 -gravity North -pointsize 12 -fill '#282828' -undercolor '#d79921' -font Iosevka -annotate +0+1 "$TEXT" $FILENAME
}

addProfile() {
    convert $FILENAME -profile /usr/share/color/icc/colord/sRGB.icc $FILENAME
}

saveAndCopy() {
    addBorder
    addShadow
    addProfile
    xclip -selection clipboard -i $FILENAME -t image/png
    notify-send -i $ICON "Screenshot" "Copied to clipboard"
}

OPTIONS=$(echo -e "Window\nFullscreen\nRectange" | $DMENU)
case $OPTIONS in
Window) takeOnWindow ;;
Fullscreen) takeOnFullScreen ;;
Rectange) takeOnRectange ;;
esac
