#!/bin/bash
# File              : dmenu_ffmpeg
# License           : MIT License
# Author            : M. Nabil Adani <nblid48[at]gmail[dot]com>
# Date              : Minggu, 28/02/2021 11:41 WIB
# Last Modified Date: Senin, 01/03/2021 11:31 WIB
# Last Modified By  : M. Nabil Adani <nblid48[at]gmail[dot]com>
# Inspired By       : https://github.com/tanuj101/awesome-dmenu/blob/master/recorder/dmenurecord.sh

DMENU="rofi -dmenu -lines 5 -width 30 -i -p Record"
OUTDIR="$HOME/Videos"
recordid="/tmp/recordid"

function audioVideo() {
    notify-send "Start Recording" "With:\nVideo On\nAudio On"

    filename="$OUTDIR/video-$(date '+%y%m%d-%H%M-%S').mkv"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -y -f x11grab -framerate 30 -s $dimensions \
        -i :0.0 -f alsa -i default \
        -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 \
        -c:a aac $filename &

    echo $! >$recordid
}

function video() {
    notify-send "Start Recording" "With:\nVideo On\nAudio Off"

    filename="$OUTDIR/video-$(date '+%y%m%d-%H%M-%S').mp4"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -y -f x11grab -framerate 30 -s $dimensions \
        -i :0.0 -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 \
        -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 $filename &

    echo $! >$recordid
}

function audio() {
    notify-send "Start Recording" "With:\nVideo Off\nAudio On"

    filename="$OUTDIR/audio-$(date '+%y%m%d-%H%M-%S').mp3"
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')
    ffmpeg -f alsa -i default -ac 2 -acodec libmp3lame -ab 128k $filename &

    echo $! >$recordid
}

function stream() {
    output=$2
    platform=$1
    dimensions=$(xdpyinfo | grep dimensions | awk '{print $2;}')

    notify-send "Start Streaming On $platform" "With:\nVideo On\nAudio On"
    ffmpeg -y -f x11grab -framerate 23 -s $dimensions \
        -i :0.0 -f alsa -i default \
        -c:v libx264 -pix_fmt yuv420p -preset veryfast -q:v 1 \
        -b:v 500k -b:a 128k \
        -vf scale=854x480 \
        -f flv $output &

    echo $1 >$recordid
}

function getStreamToken() {
    $DMENU -mesg "Insert $1 Token" -lines 0
}

function startStreaming() {
    platform="$1"
    streamurl="$2"
    token=$(getStreamToken "$platform")

    if [ -z "$token" ]; then
        exit
    else
        stream "$platform" "$streamurl$token"
    fi
}

function streamOnFacebook() {
    startStreaming "Facebook" "rtmps://live-api-s.facebook.com:443/rtmp/"
}

function streamOnNimoTv() {
    startStreaming "Nimo TV" "rtmp://txpush.rtmp.nimo.tv/live/"
}

function streamOnTwitch() {
    startStreaming "Twitch" "rtmp://sin.contribute.live-video.net/app/"
}

function streamOnYoutube() {
    startStreaming "Youtube" "rtmp://a.rtmp.youtube.com/live2/"
}

function streamOnVimeo() {
    startStreaming "Vimeo" "rtmps://rtmp-global.cloud.vimeo.com:443/live/"
}

function stoprecord() {
    if [ -f $recordid ]; then
        kill -15 $(cat $recordid)
        rm $recordid
    fi

    sleep 5
    if [ "$(pidof ffmpeg)" != "" ]; then
        pkill ffmpeg
    fi
}


function endrecord() {
    OPTIONS='["Yes", "No"]'
    select=$(echo $OPTIONS | jq -r ".[]" | $DMENU -mesg "Stop Recording")
    [ "$select" == "Yes" ] && stoprecord
}

function startrecord() {
    OPTIONS='''
    [
        ["難 Audio Video",        "audioVideo"],
        ["  Video Only",         "video"],
        ["  Audio Only",         "audio"],
        ["  Stream On Facebook", "streamOnFacebook"],
        ["壘 Stream On Nimo TV",  "streamOnNimoTv"],
        ["既 Stream On Twitch",   "streamOnTwitch"],
        ["  Stream On Youtube",  "streamOnYoutube"],
        ["  Stream On Vimeo",    "streamOnVimeo"]
    ]
    '''
    select=$(echo $OPTIONS | jq -r ".[][0]" | $DMENU)
    eval $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$select\") | .[1]")
}

if [ -f $recordid ]; then
    endrecord
else
    startrecord
fi
