#!/bin/bash
# File              : dmenu_sudo
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Rabu, 10/06/2020 06:45 WIB
# Last Modified Date: Rabu, 10/06/2020 06:45 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>

rofi -dmenu -password -p "password for $USER:" -lines 0
