#!/bin/bash
# File              : dmenu_mager
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Jumat, 15/05/2020 13:12 WIB
# Last Modified Date: Minggu, 11/10/2020 12:44 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>

DMENU="rofi -dmenu -i -p Mager"
# OPTIONS = [[label, command]]
OPTIONS='''
[
  [ "aria2",                  "dmenu_aria2" ],
  [ "boottester",             "dmenu_boottester" ],
  [ "droidcam audio only",    "droidcam-cli -a 192.168.43.1 4747 &" ],
  [ "droidcam video & audio", "droidcam-cli -a -v 192.168.43.1 4747 &" ],
  [ "droidcam video only",    "droidcam-cli 192.168.43.1 4747 &" ],
  [ "play video0",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video0 --vf=hflip --profile=low-latency --untimed" ],
  [ "play video1",            "mpv --no-audio --window-scale=0.5 av://v4l2:/dev/video1 --vf=hflip --profile=low-latency --untimed" ],
  [ "kill",                   "dmenu_kill" ],
  [ "kill droidcam",          "pkill droidcam-cli" ],
  [ "monitor",                "dmenu_monitor" ],
  [ "mpdmenu",                "dmenu_mpdmenu" ],
  [ "mpv",                    "dmenu_mpv" ],
  [ "pass",                   "dmenu_pass -p \"Pass Man\"" ],
  [ "power",                  "dmenu_power" ],
  [ "qutebrowser",            "dmenu_qutebrowser" ],
  [ "record",                 "dmenu_record" ],
  [ "droidapps",              "droidapps" ],
  [ "screenshot",             "dmenu_screenshot" ],
  [ "switcher",               "dmenu_switcher" ],
  [ "sxhkd",                  "dmenu_sxhkd" ],
  [ "systemd",                "dmenu_systemd" ],
  [ "todo",                   "dmenu_todo" ],
  [ "translate",              "dmenu_translate -i" ],
  [ "udiskie",                "dmenu_udiskie -matching regex -dmenu -i -no-custom -multi-select -p FlashDrive" ],
  [ "wifi",                   "dmenu_wifi" ],
  [ "window",                 "dmenu_window" ],
  [ "youtube",                "ytfzf -fDH" ],
  [ "umount iso",             "dmenu_iso" ],
  [ "iptv",                   "dmenu_iptv" ],
  [ "virtual session",        "dmenu_virtualsession" ],
  [ "dns switcher",           "dmenu_dns"],
  [ "adb clipoard",           "adbclip"],
  [ "virt viewer",           "dmenu_virt"]
]
'''

label=$(echo $OPTIONS | jq -r "sort | .[][0]" | $DMENU)
exec $(echo $OPTIONS | jq -r ".[] | select(.[0] == \"$label\") | .[1]")
