#!/bin/bash
# File              : dmenu_aria2
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Rabu, 06/11/2019 04:51 WIB
# Last Modified Date: Kamis, 23/04/2020 12:51 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>


# required 
# 1. aria2p (https://github.com/pawamoy/aria2p)
# 2. clipmenu (https://github.com/cdown/clipmenu)

url=$(cat /tmp/clipmenu/*/line_cache | sort -r | cut -c 21- | grep -Po '(http|https|ftp|ftps):\/\/\w.+' | dmenu -p Aria2 "$@")
# url=$(clipdel '^http[s]:\/\/.*' | sort -r | dmenu -p Aria2 "$@")
if [[ ! -z $url ]]; then
  notify-send "Aria2 | Downloading" "$url" -u normal
  aria2p call addUri -J "[[\"$url\"]]"
fi
