#!/usr/bin/env bash
# Repository : https://github.com/zbaylin/rofi-wifi-menu (original source)

# Starts a scan of available broadcasting SSIDs
# nmcli dev wifi rescan

DMENU="rofi -dmenu -i $@"
FIELDS=SSID,SECURITY
LIST=$(nmcli --fields "$FIELDS" device wifi list | sed '/^--/d')
# Gives a list of known connections so we can parse it later
KNOWNCON=$(nmcli connection show)
# Really janky way of telling if there is currently a connection
CONSTATE=$(nmcli -fields WIFI g)
CURRSSID=$(LANGUAGE=C nmcli -t -f active,ssid dev wifi | awk -F: '$1 ~ /^yes/ {print $2}')

if [[ "$CONSTATE" =~ "enabled" ]]; then
  TOGGLE="toggle off"
elif [[ "$CONSTATE" =~ "disabled" ]]; then
  TOGGLE="toggle on"
fi

CHENTRY=$(echo -e "$TOGGLE\nmanual\n$LIST" | uniq -u | $DMENU -p "Wi-Fi SSID:" )
CHSSID=$(echo "$CHENTRY" | sed  's/\s\{2,\}/\|/g' | awk -F "|" '{print $1}')

# If the user inputs "manual" as their SSID in the start window, it will bring them to this screen
if [ "$CHENTRY" = "manual" ] ; then
  # Manual entry of the SSID and password (if appplicable)
  MSSID=$(echo "enter the SSID of the network (SSID,password)" | $DMENU -p "Manual Entry" )
  # Separating the password from the entered string
  MPASS=$(echo "$MSSID" | awk -F "," '{print $2}')

  # If the user entered a manual password, then use the password nmcli command
  if [ "$MPASS" = "" ]; then
    nmcli dev wifi con "$MSSID"
  else
    nmcli dev wifi con "$MSSID" password "$MPASS"
  fi

elif [ "$CHENTRY" = "toggle on" ]; then
  nmcli radio wifi on

elif [ "$CHENTRY" = "toggle off" ]; then
  nmcli radio wifi off

else

  # If the connection is already in use, then this will still be able to get the SSID
  if [ "$CHSSID" = "*" ]; then
    CHSSID=$(echo "$CHENTRY" | sed  's/\s\{2,\}/\|/g' | awk -F "|" '{print $3}')
  fi

  # Parses the list of preconfigured connections to see if it already contains the chosen SSID. This speeds up the connection process
  if [[ $(echo "$KNOWNCON" | grep "$CHSSID") = "$CHSSID" ]]; then
    nmcli con up "$CHSSID"
  else
    if [[ "$CHENTRY" =~ "WPA2" ]] || [[ "$CHENTRY" =~ "WEP" ]]; then
      WIFIPASS=$(echo "if connection is stored, hit enter" | $DMENU -p "Password" -P )
      fi
      nmcli dev wifi con "$CHSSID" password "$WIFIPASS"
    fi

  fi
