#!/bin/bash
# File              : jack2pulse
# License           : MIT License
# Author            : M. Nabil Adani <nblid48@gmail.com>
# Date              : Selasa, 21/04/2020 09:35 WIB
# Last Modified Date: Selasa, 21/04/2020 09:35 WIB
# Last Modified By  : M. Nabil Adani <nblid48@gmail.com>

killall -9 pulseaudio
killall -9 jackdbus
killall -9 carla
jackdbus auto &
pulseaudio --daemonize --high-priority --realtime --exit-idle-time=-1 --file=/usr/share/cadence/pulse2jack/play+rec.pa -n &
carla --no-gui ~/Dotfiles/carla/musik.carxp &
