#!/bin/bash

cat ~/.config/sxhkd/*.sxhkdrc | tee /tmp/sxhkdrc > /dev/null
if [[ $(pidof sxhkd) ]]; then
    killall -9 sxhkd
    notify-send -i $HOME/Dotfiles/icons/gruvbox/keyboard.png "sxhkd" "restart sxhkd"
fi
sxhkd -c /tmp/sxhkdrc &
