#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2021 M. Nabil Adani <nblid48[at]gmail[dot]com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# dependency
# 1. gdown (https://github.com/wkentaro/gdown)
# 2. libtmux (https://github.com/tmux-python/libtmux)

from urllib import parse
import libtmux
import os

tmux = libtmux.Server()
session_name = "gdown"
url = os.getenv("QUTE_URL")


def getId(url: str) -> str:
    parsed = parse.urlsplit(url)
    if parsed.query:
        parsed = parse.parse_qsl(parsed.query)
        gid = dict(parsed)
        return gid["id"]
    return parsed.path.split("/")[3]


if tmux.has_session(session_name):
    session = tmux.find_where({"session_name": session_name})
else:
    session = tmux.new_session(session_name, attach=False)

command = f'cd ~/Downloads && gdown -c --id "{getId(url)}"'
session.new_window(attach=False, window_shell=f"fish -c '{command}'")
