#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2021 M. Nabil Adani <nblid48[at]gmail[dot]com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# dependency
# 1. gdown (https://github.com/wkentaro/gdown)

from typing import Tuple, Type, Union
from urllib import parse
import shlex
from subprocess import Popen, PIPE


def getId(url: str) -> str:
    parsed = parse.urlsplit(url)
    parsed = parse.parse_qsl(parsed.query)
    gid = dict(parsed)
    return gid["id"]


def shell(command: str) -> Union[str, bool]:
    cmd = shlex.split(command)
    output, err = Popen(cmd, stdout=PIPE, stderr=PIPE).communicate()
    if err:
        pass


def tmuxSendKey(value: str) -> bool:
    # tmux send-keys -t mySession.0 "echo 'Hello World'" ENTER
    pass


print(shell("ls /"))
